### PR TITLE
(Sonar) Fixed finding: "@Override should be used on overriding and implementing methods"

### PR DESCRIPTION
**Pull request by pixeeai**
## Remediation

This change fixes "`@Override` should be used on overriding and implementing methods" (id = [java:S1161](https://rules.sonarsource.com/java/RSPEC-1161/)) identified by Sonar.

## Details

This change adds missing `@Override` to known subclasses. Documenting inheritance will help readers and static analysis tools understand the code better, spot bugs easier, and in general lead to more efficient and effective review.

Our changes look something like this:

```diff
  interface AcmeParent {
     void doThing();
  } 

  class AcmeChild implements AcmeParent {

+   @Override
    void doThing() {
      thing();
    }
    
  }
```

<details>
  <summary>More reading</summary>

  * [https://rules.sonarsource.com/java/RSPEC-1161/](https://rules.sonarsource.com/java/RSPEC-1161/)
</details>
🧚🤖  Powered by Pixeebot  

[Feedback](https://ask.pixee.ai/feedback) | [Community](https://pixee-community.slack.com/signup#/domain-signup) | [Docs](https://docs.pixee.ai/) | Codemod ID: [sonar:java/add-missing-override-s1161](https://docs.pixee.ai/codemods/java/sonar_java_add-missing-override-s1161)

### CODE REVIEW

**Comment by pixeeai** [comment]
This change was autogenerated from a GitHub app - called [Pixeebot](https://github.com/marketplace/pixeebot-automated-code-fixes). A code-quality GitHub App; like Dependabot, but for source code. Feel free to check it our for more details for how you can install it onto your project's repo for continued code hardening and code security recommendations. 👍

**Comment by manuelleduc** [comment]
This PR is very limited, an accurate PR would fix all the missing override annotations at once.

**Comment by vmassol** [comment]
@manuelleduc sure but we should still apply it IMO as it looks good

**Comment by pixeeai** [comment]
Any chance you've had the time to review these changes or had any additional discussion about it?

If you're not interested implementing them at this time, no worries. I can close the PR and follow up with additional changes in the future. Also, this plugin is free for non-commercial open sourced projects, so feel free to give it an install if you want to see the other recommended PRs. ([Pixeebot | Automated code fixes. · GitHub Marketplace](https://github.com/marketplace/pixeebot-automated-code-fixes))

Thanks,
Zach

**Comment by vmassol** [comment]
@michitux I'm not sure I agree with:

> XWiki normally doesn't meet the definition of "non-commercial open source project"

Depends if by "XWiki" you mean xwiki.org or xwiki.com. If you mean xwiki.org then I don't agree or if I agree then any project from the Apache Software Foundation would also not qualify as "non-commercial open source project" as sponsoring and active developers come from companies having an interest in the software developer (and paying for its dev). Exactly the same as xwiki.org. That's why we have an independent governance.

**Comment by michitux** [comment]
@vmassol I was referring to companies like Jetbrains (and iirc there was also another concrete example, but I don't remember which one) that provide free tools to non-commercial open source projects where XWiki doesn't fit into the definition.

**Comment by vmassol** [comment]
@michitux I've discussed a few times with Jetbrains about this in the past :) And the outcome is that they were not really able to tell me the difference between xwiki.org and the ASF, but in the end,  they're the one deciding and they said they made some special decisions to have free licenses for ASF members (and others, see https://www.jetbrains.com/community/opensource/).

Now I don't see the exact rules anymore under "Collaborate with us to power up your open-source project" on https://www.jetbrains.com/community/opensource/, maybe they've changed the rules. They just say: 

> We prioritize open-source projects that are actively maintained, have a dedicated community, and make valuable contributions to the software industry. 

https://www.jetbrains.com/shop/eform/opensource seems pretty generic too.

More generally speaking, other companies we've discussed with and which have open-source programmes, were happy to give us oss licenses.

**Pull request merged**
